spring:
  datasource:
    url: jdbc:mariadb://172.17.0.1:3306/app1_prod?useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=Asia/Seoul
    username: sbsst
    password: sbs123414
  jpa:
    hibernate:
      ddl-auto: none
logging:
  level:
    root: info
    com.sbs.tutorial.app1: info
custom:
  genFileDirPath: /gen
